TravelProject/siteapp/urls.py
# This is siteapp's urls
# this app is created to show that we can create more than one app

from . import views
from django.urls import path
app_name='siteapp'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),


]

TravelProject/webapp/urls.py
# This is webapp url
from . import views
from django.urls import path

app_name='webapp'
urlpatterns = [
    path('', views.home, name='out'),
    path('news', views.news, name='news'),
    path('home', views.home, name='home'),
    path('elements',views.elements,name='elements'),
    path('contact',views.contact,name='contact'),
    path('destinations',views.destinations,name='destinations')

]

TravelProject/websi/urls.py
from django.contrib import admin
from django.urls import path, include

from websi import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('reg/', include('siteapp.urls')),
    path('news/',include('webapp.urls')),
    path('home/',include('webapp.urls')),
    path('contact/',include('webapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


#virtualenv name="web"

TravelProject/siteapp/models.py
from django.db import models

# Create your models here.

TravelProject/webapp/models.py
from django.db import models

# Create your models here.
class Place(models.Model):
    name=models.CharField(max_length=250)
    img=models.ImageField(upload_to='pics')
    desc=models.TextField()
#def nammal admim pageil kodutha name ath pole kannan vendiann def __str__(self) use cheyune
    def __str__(self):
        return self.name

#meet the team
class Team(models.Model):
    Name=models.CharField(max_length=300)
    Img=models.ImageField(upload_to='photo')
    Role=models.TextField()
    def __str__(self):
        return self.Name

TravelProject/siteapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'invalid user')
            return redirect('login')
    return render(request, 'login.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email_id = request.POST['email_id']
        password = request.POST['password']
        conpassword = request.POST['password1']
        if password == conpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username Taken")
                return redirect('register')
            elif User.objects.filter(email=email_id).exists():
                messages.info(request, "email Taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                                email=email_id, password=password)
                user.save();
                return redirect('login')
                print('USER CREATED')
        else:
            messages.info(request, "Password not matching")
            return redirect('register')
        return redirect('/')

    return render(request, 'register.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

TravelProject/webapp/views.py
# Create your views here.

from django.shortcuts import render, redirect
from .models import Place
from .models import Team


def news(request):
    return render(request, 'news.html')


def home(request):
    obj = Place.objects.all()  # ORM form
    team = Team.objects.all()
    return render(request, "index.html", {'result': obj, 'team': team})



def elements(request):
    return render(request, 'elements.html')


def contact(request):
    return render(request,'contact.html')


def destinations(request):
    return render(request,'destinations.html')

TravelProject/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Contact</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">
</head>
<body>

<div class="super_container">
	
	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
							<div class="logo"><a href="{% url 'webapp:home' %}">Travell Buddy</a></div>
							<nav class="main_nav">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									<li ><a href="{% url 'webapp:home' %}">Home</a></li>
									<li ><a href="{% url 'webapp:destinations' %}">Destinations</a></li>
									<li ><a href="{% url 'webapp:contact' %}">Contact Us</a></li>
									{% if user.is_authenticated %}
									<li class="user">Hai {{user.username}}</li>
									<li><a href="reg/logout">Logout</a></li>
									{% else %}
									<li><a href="reg/register" >Register</a></li>
									<li><a href="reg/login" class="login" >Login</a></li>
									{% endif %}
								</ul>
							</nav>
							<div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>

							<!-- Hamburger -->

							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header_social d-flex flex-row align-items-center justify-content-start">
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</header>

	<!-- Menu -->

	<div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">
			<div class="menu_logo"><a href="index.html">Travel Buddy</a></div>
			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
		<div class="menu_content">
			<ul>
				<li ><a href="{% url 'webapp:home' %}">Home</a></li>
				<li ><a href="{% url 'webapp:destinations' %}">Destinations</a></li>
				<li ><a href="{% url 'webapp:contact' %}">Contact Us</a></li>
				{% if user.is_authenticated %}
				<li class="user">Hai {{user.username}}</li>
				<li><a href="reg/logout">Logout</a></li>
				{% else %}
				<li><a href="reg/register" >Register</a></li>
				<li><a href="reg/login" class="login" >Login</a></li>
				{% endif %}
			</ul>
		</div>
		<div class="menu_social">
			<div class="menu_phone ml-auto">Call us: 00-56 445 678 33</div>
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
	
	<!-- Home -->

	<div class="home">
		<div class="background_image" style="background-image:url({% static 'images/contact.jpg' %})"></div>
	</div>

	<!-- Search -->

	<div class="home_search">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="home_search_container">
						<div class="home_search_title">Search for your trip</div>
						<div class="home_search_content">
							<form action="#" class="home_search_form" id="home_search_form">
								<div class="d-flex flex-lg-row flex-column align-items-start justify-content-lg-between justify-content-start">
									<input type="text" class="search_input search_input_1" placeholder="City" required="required">
									<input type="text" class="search_input search_input_2" placeholder="Departure" required="required">
									<input type="text" class="search_input search_input_3" placeholder="Arrival" required="required">
									<input type="text" class="search_input search_input_4" placeholder="Budget" required="required">
									<button class="home_search_button">search</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Contact -->

	<div class="contact">
		<div class="container">
			<div class="row">

				<!-- Get in touch -->
				<div class="col-lg-6">
					<div class="contact_content">
						<div class="contact_title">Get in touch with us</div>
						<div class="contact_text">
							<p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet. Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.</p>
						</div>
						<div class="contact_list">
							<ul>
								<li>
									<div>address:</div>
									<div>1481 Creekside Lane Avila Beach, CA 931</div>
								</li>
								<li>
									<div>phone:</div>
									<div>+53 345 7953 32453</div>
								</li>
								<li>
									<div>email:</div>
									<div>yourmail@gmail.com</div>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Contact Form -->
				<div class="col-lg-6">
					<div class="contact_form_container">
						<form action="#" id="contact_form" class="contact_form">
							<div style="margin-bottom: 18px"><input type="text" class="contact_input contact_input_name inpt" placeholder="Your Name" required="required"><div class="input_border"></div></div>
							<div class="row">
								<div class="col-lg-6" style="margin-bottom: 18px">
									<div><input type="text" class="contact_input contact_input_email inpt" placeholder="Your E-mail" required="required"><div class="input_border"></div></div>
								</div>
								<div class="col-lg-6" style="margin-bottom: 18px">
									<div><input type="text" class="contact_input contact_input_subject inpt" placeholder="Subject" required="required"><div class="input_border"></div></div>
								</div>
							</div>
							<div><textarea class="contact_textarea contact_input inpt" placeholder="Message" required="required"></textarea><div class="input_border" style="bottom:3px"></div></div>
							<button class="contact_button">send</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Map -->

	<div class="contact_map">
		<!-- Google Map -->
		<div class="map">
			<div id="google_map" class="google_map">
				<div class="map_container">
					<div id="map"></div>
				</div>
			</div>
		</div>
	</div>

	<!-- Footer -->

	<footer class="footer">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/footer_1.jpg' %}" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter">
						<div class="newsletter_title_container text-center">
							<div class="newsletter_title">Subscribe to our newsletter to get the latest trends & news</div>
							<div class="newsletter_subtitle">Join our database NOW!</div>
						</div>
						<div class="newsletter_form_container">
							<form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
								<div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
									<div><input type="text" class="newsletter_input newsletter_input_name inpt" id="newsletter_input_name" placeholder="Name" required="required"><div class="input_border"></div></div>
									<div><input type="email" class="newsletter_input newsletter_input_email inpt" id="newsletter_input_email" placeholder="Your e-mail" required="required"><div class="input_border"></div></div>
								</div>
								<div><button class="newsletter_button">subscribe</button></div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row footer_contact_row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/sign.svg' %}" alt=""></div>
								<div class="footer_contact_title">give us a call</div>
								<div class="footer_contact_list">
									<ul>
										<li>Office Landline: +44 5567 32 664 567</li>
										<li>Mobile: +44 5567 89 3322 332</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/trekking.svg' %}" alt=""></div>
								<div class="footer_contact_title">come & drop by</div>
								<div class="footer_contact_list">
									<ul style="max-width:190px">
										<li>4124 Barnes Street, Sanford, FL 32771</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/around.svg' %}" alt=""></div>
								<div class="footer_contact_title">send us a message</div>
								<div class="footer_contact_list">
									<ul>
										<li>youremail@gmail.com</li>
										<li>Office@yourbusinessname.com</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<div class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>
	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>
</body>
</html>

TravelProject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<style>
  body{
    margin: 0;
    width: 100%;
    height: 500px;
    background-color:pink;
  }
  .login{
    width: 300px;
    height: 270px;
    background-color: yellowgreen;
    margin-top: 175px;
    margin-left: 500px;
   
  }
  .title{
     text-align: center;
     padding-top: 26px;
  }
  .user{
     margin-left: 55px;
    padding: 2px;
    text-align: center;
  }
  .pass{
     margin-left: 55px;
    padding: 2px;
    text-align: center;
    margin-top:18px;
  }
  .submit{
  margin-left: 112px;
    margin-top: 26px;
    }
</style>
<body>
  <div class="login">
      <h1 class="title">LOGIN</h1>
<form  action="login" method="POST">
    {% csrf_token %}
  <input class="user" type="text"  name="username" placeholder="Enter your Username"><br>
  <input class="pass" type="password" name="password" placeholder="Enter your Password"><br>
  <input class="submit" type="submit">
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}</div>
</body>
</html>

TravelProject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<style>
    body{
        margin: 0;
        width: 100px;
        height: 500px;
        background-color: blueviolet;
    }
    .register{
        height: 320px;
        width: 270px;
        background-color: violet;
        margin-top: 153px;
        margin-left: 516px;
    }
    .title{
    text-align: center;
    padding: 8px;
    }
    .user{
    margin-left: 40px;
    text-align: center;
    }
    .first{
    margin-left: 40px;
    text-align: center;
    margin-top: 7px;
    }
    .second{
    margin-left: 40px;
    text-align: center;
    margin-top: 7px;
    }
    .email{
    margin-left: 40px;
    text-align: center;
    margin-top: 7px;
    }
    .pass{
    margin-left: 40px;
    text-align: center;
    margin-top: 7px;
    }
    .pass2{
    margin-left: 40px;
    text-align: center;
    margin-top: 7px;
    }
    .sub{
    margin-left: 95px;
    text-align: center;
    margin-top: 15px;
    }
</style>
<body>

<div class="register">
<h1 class="title" >Registration</h1>
<form action="register" method="POST">
    {% csrf_token %}
    <input type="text" class="user" name="username" placeholder="Enter your username"><br>
       <input type="text" class="first" name="first_name" placeholder="Enter your first name"><br>
       <input type="text" class="second" name="last_name" placeholder="Enter your last name"><br>
       <input type="email" class="email" name="email_id" placeholder="Enter your email id"><br>
       <input type="password" class="pass" name="password" placeholder="Enter your password"><br>
     <input type="password" class="pass2" name="password1" placeholder="Confirm your password"><br>
    <input class="sub" type="submit">
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</div>
</body>
</html>